baseURL = "https://novel.1001k.com/"
languageCode = "zh-cn"
title = "故事鸟"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
sectionPagesMenu = "main"
[pagination]
pagerSize = 10
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 1
[[menu.main]]
name = "搜索"
url = "/search/"
weight = 4
[params]
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableThemeToggle = true

[params.label]
text = "故事鸟"
icon = "/images/logo.png"
iconHeight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[[permalinks]]
  pattern = '/category/:sections[last]/'
  [permalinks.target]
    kind = 'section'

[[permalinks]]
  pattern = '/post/:slug/'
  [permalinks.target]
    kind = 'page'
    path = '/short/**'

[[permalinks]]
  pattern = '/post/:slug/'
  [permalinks.target]
    kind = 'page'
    path = '/serial/**'

